WITH 
DIASPAGOPROMESAS AS (
SELECT DISTINCT DATE_TRUNC(EFECTIVA_MES_FECHA, MONTH) AS MES, CONTRATO, 
CASE 
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 0 THEN "0"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 1 THEN "1"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 2 THEN "2"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 3 THEN "3"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 4 THEN "4"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 5 THEN "5"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 6 THEN "6"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 7 THEN "7"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) = 8 THEN "8"
WHEN DATE_DIFF(DATE(PP_FECHA), EFECTIVA_MES_FECHA,DAY) >= 9 THEN "9+"
END AS DIASPROMESA
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-24_CR_REPORTE_GESTION_UNICAS_CLEAN_2021_D`
WHERE PROMESA = "SI" AND DATE(PP_FECHA) > EFECTIVA_MES_FECHA
GROUP BY MES, CONTRATO, DIASPROMESA
),
PAGOANTES AS(
  SELECT  C.Contrato AS CONTRATO_ID
  , DATE_TRUNC(C.FECHA_ASIGNACION, MONTH) AS MES_ASIGNACION
  FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D` C
  WHERE DATE_DIFF(c.FECHA_PAGO, C.FECHA_FACTURA, DAY) <= 90
  GROUP BY CONTRATO_ID, MES_ASIGNACION
),
CRUCE AS(
SELECT d.MES AS MES , d.DIASPROMESA AS NUMDIAS , d.Contrato AS CONTRATO,
CASE WHEN p.CONTRATO_ID IS NULL THEN "NO PAGO"
WHEN p.CONTRATO_ID IS NOT NULL THEN "PAGO"
END AS PAYFLAG
FROM DIASPAGOPROMESAS d LEFT JOIN PAGOANTES p ON d.Contrato = p.CONTRATO_ID AND d.MES = p.MES_ASIGNACION
GROUP BY MES, NUMDIAS,CONTRATO, PAYFLAG)
SELECT c.MES AS MES , c.NUMDIAS AS DIASPROM, count(DISTINCT c.CONTRATO ) AS NUMCONTRATOS
FROM CRUCE c
--WHERE c.PAYFLAG = "NO PAGO"
WHERE c.PAYFLAG = "PAGO"
GROUP BY MES, DIASPROM
ORDER BY MES, DIASPROM
