SELECT DISTINCT EXTRACT(MONTH FROM FECHA_FACTURA)AS MES, COUNT(DISTINCT CONTRATO)
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
WHERE
    (DATE_DIFF(FECHA_PAGO, FECHA_FACTURA, DAY)> 21)
    OR (FECHA_PAGO IS NULL
   AND RANGO_CONTRATO = "1-SIN VENCER") 
AND TIPO_SERVICIO IN ('INTERNET', 'CABLE TICA', 'TELEFONIA', 'FTTH (JASEC)', 'HOGARES CONECTADOS')
GROUP BY MES
ORDER BY MES
