WITH
NOTASCREDITO AS(
SELECT DEPARTAMENTO, CONTRATO, FECHA_APERTURA as InicioTicket, FECHA_FINALIZACION as FinTicket
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_TIQUETES_SERVICIO_2021-01_A_2021-11_D` 
WHERE 
CLASE IS NOT NULL AND MOTIVO IS NOT NULL AND CONTRATO IS NOT NULL AND FECHA_APERTURA IS NOT NULL 
AND SUBAREA <> "0 A 30 DIAS" AND SUBAREA <> "30 A 60 DIAS" AND SUBAREA <> "60 A 90 DIAS" 
AND SUBAREA <> "90 A 120 DIAS" AND SUBAREA <> "120 A 150 DIAS" AND SUBAREA <> "150 A 180 DIAS" 
AND SUBAREA <> "MAS DE 180" AND ESTADO <> "ANULADA"
AND MOTIVO="CONSULTAS DE FACTURACION O COBRO"
AND (AREA="NOTAS DE CREDITOS" OR AREA="NOTAS DE CREDITO")
GROUP BY DEPARTAMENTO, CONTRATO, FECHA_APERTURA, FECHA_FINALIZACION)
SELECT EXTRACT (MONTH FROM InicioTicket) as MES, DEPARTAMENTO, COUNT(CONTRATO) AS NUMREG
FROM NOTASCREDITO 
GROUP BY MES, DEPARTAMENTO
ORDER BY MES, NUMREG DESC 
