WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(DATE(CST_CHRN_DT)) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING DATE_TRUNC(Maxfecha, MONTH) = DATE_TRUNC(MAX(FECHA_EXTRACCION), MONTH)
),
CRUCECHURNERSPREVIOS AS(
    SELECT DISTINCT t.ACT_ACCT_CD as Previos, c.ACT_ACCT_CD as Churners, c.MaxFecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
    RIGHT JOIN CHURNERSCRM c ON c.ACT_ACCT_CD = t.ACT_ACCT_CD AND  DATE(CST_CHRN_DT) < MaxFecha AND DATE_DIFF(MaxFecha, DATE(t.CST_CHRN_DT), DAY) <= 90
)
SELECT DATE_TRUNC(Maxfecha, MONTH) as MES, Count(DISTINCT c.Churners) AS NumChurners, COUNT (DISTINCT c.Previos) as NumChurnersPrevios
FROM CRUCECHURNERSPREVIOS c
GROUP BY MES
ORDER BY MES
