WITH 
CHURNERS AS(
     SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha,
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
     --WHERE PD_BB_PROD_ID IS NOT NULL
    WHERE PD_TV_PROD_ID IS NOT NULL
    --WHERE PD_VO_PROD_ID IS NOT NULL
GROUP BY ACT_ACCT_CD
 HAVING EXTRACT (MONTH FROM MAX(CST_CHRN_DT)) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
CRUCECHURN AS
(
 SELECT DISTINCT c.ACT_ACCT_CD, c.Maxfecha, c_cust_age
 FROM CHURNERS c INNER JOIN `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D` t
 ON c.ACT_ACCT_CD = t.ACT_ACCT_CD AND c.Maxfecha = t.CST_CHRN_DT
 GROUP BY c.ACT_ACCT_CD, c.Maxfecha, c_cust_age
),
TENURE AS(
     SELECT DISTINCT ACT_ACCT_CD, c.Maxfecha,
   CASE WHEN Max(C_CUST_AGE) <= 6 THEN "6M"
        WHEN Max(C_CUST_AGE) > 6 AND Max(C_CUST_AGE) <= 12 THEN "6M-1Y"
        WHEN Max(C_CUST_AGE) > 12 AND Max(C_CUST_AGE) <= 24 THEN "1Y-2Y"
        WHEN Max(C_CUST_AGE) > 24 THEN "2Y+"
        END AS TENURE,
    FROM CRUCECHURN c
    GROUP BY ACT_ACCT_CD, c.Maxfecha)

SELECT DISTINCT EXTRACT (MONTH FROM t.Maxfecha) as MES, t.TENURE, Count(DISTINCT t.ACT_ACCT_CD) AS Churners
FROM TENURE t
GROUP BY MES, TENURE
ORDER BY MES, TENURE ASC
