WITH CHURNERSTV AS(
     SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOSTV, MAX(CST_CHRN_DT) AS MaxfechaTV
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_TV_PROD_ID IS NOT NULL
    GROUP BY CONTRATOSTV
    HAVING EXTRACT (MONTH FROM MaxfechaTV) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSTV AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('CABLE TICA',  'HOGARES CONECTADOS') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA
),
CRUCECOLLECTIONSTV AS(
    SELECT DISTINCT CONTRATOSTV, CONTRATO, MaxfechaTV
    FROM CHURNERSTV LEFT JOIN MOROSOSTV ON CONTRATOSTV = CONTRATO AND DATE_DIFF (MaxfechaTV, FECHA_FACTURA, DAY) >= 90
    GROUP BY CONTRATOSTV, CONTRATO,MaxfechaTV
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOSTV, MaxfechaTV,
    CASE WHEN CONTRATO IS NULL THEN "Voluntario"
    WHEN CONTRATO IS NOT NULL THEN "Involuntario"
    END AS TipoChurn
    FROM CRUCECOLLECTIONSTV
    GROUP BY CONTRATOSTV, MAXFECHATV, TipoChurn
)
SELECT EXTRACT (MONTH FROM MAXFECHATV) AS MES, TIPOCHURN, COUNT(DISTINCT CONTRATOSTV)
FROM CLASIFICACIONCHURN
GROUP BY MES, TIPOCHURN
ORDER BY MES ASC, TIPOCHURN DESC
