WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
    AND EXTRACT (MONTH FROM Maxfecha) < 12
),
INVOLUNTARYCHURNERS AS(
 SELECT DISTINCT ACT_ACCT_CD, Max(CST_CHRN_DT) AS MaxChurnInvol,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    WHERE (FI_OUTST_AGE >= 60 AND PD_BB_PROD_ID IS NOT NULL) OR (FI_OUTST_AGE >= 90 
    AND (PD_TV_PROD_ID IS NOT NULL OR PD_VO_PROD_ID IS NOT NULL))
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxChurnInvol) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
INVOLUNTARYMAXCHURNERS AS(
 SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha as  MaxChurnInvol
 FROM CHURNERSCRM c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.ACT_ACCT_CD = i.ACT_ACCT_CD AND i.MaxChurnInvol = c.MaxFecha
   WHERE i.ACT_ACCT_CD IS NOT NULL
   GROUP BY ACT_ACCT_CD, MaxFecha
),
VOLUNTARYMAXCHURNERS AS(
   SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha AS MaxChurnVol
   FROM CHURNERSCRM c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.ACT_ACCT_CD = i.ACT_ACCT_CD AND i.MaxChurnInvol = c.MaxFecha
   WHERE i.ACT_ACCT_CD IS NULL
   GROUP BY ACT_ACCT_CD, MaxFecha
),
CHURNERSMES AS(
    SELECT EXTRACT (MONTH FROM Maxfecha) as MES, Count(DISTINCT ACT_ACCT_CD) AS NumChurners
    FROM CHURNERSCRM
    GROUP BY MES
    ORDER BY MES
),
CHURNMESINVOL AS(
    SELECT EXTRACT (MONTH FROM MaxChurnInvol) as MES, Count(DISTINCT ACT_ACCT_CD) AS NumInvol
    FROM INVOLUNTARYMAXCHURNERS 
    GROUP BY MES
    ORDER BY MES
),
CHURNMESVOL AS(
    SELECT EXTRACT (MONTH FROM MaxChurnVol) as MES, Count(DISTINCT ACT_ACCT_CD) AS NumVol
    FROM VOLUNTARYMAXCHURNERS 
    GROUP BY MES
    ORDER BY MES
),
CONTRATOSVOLUNTARIOS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD),10) AS ACT_ACCT_CD, MaxChurnVol
FROM VOLUNTARYMAXCHURNERS
GROUP BY ACT_ACCT_CD, MaxChurnVol),

NORETENIDOS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',Contrato) ,10) AS Contrato, MAX(FECHA_FINALIZACION) AS FechaTiquete
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL AND SOLUCION_FINAL="NO RETENIDO"
AND EXTRACT(YEAR FROM FECHA_FINALIZACION)=2021
GROUP BY Contrato
HAVING EXTRACT (MONTH FROM FechaTiquete) < 12
),

CONTRATOSNORET AS(
SELECT DISTINCT EXTRACT(MONTH FROM FechaTiquete) as Mesret, CONTRATO
FROM NORETENIDOS
WHERE EXTRACT(YEAR FROM FechaTiquete)=2021
)
SELECT 
--v.MES, 
COUNT(DISTINCT V.ACT_ACCT_CD) AS ChurnersVol, COUNT (DISTINCT r.contrato) as NumNoRet
FROM CONTRATOSVOLUNTARIOS v LEFT JOIN CONTRATOSNORET r ON v.ACT_ACCT_CD=r.Contrato
--GROUP BY v.MES ORDER BY v.MES
