WITH CHURNERSCRMTV AS(
     SELECT DISTINCT ACT_ACCT_CD AS CONTRATOTV, MAX(CST_CHRN_DT) AS MaxfechaTV
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    WHERE PD_TV_PROD_ID IS NOT NULL
    GROUP BY CONTRATOTV
    HAVING EXTRACT (MONTH FROM MaxfechaTV) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
INVOLUNTARYCHURNERS AS(
 SELECT DISTINCT ACT_ACCT_CD, Max(CST_CHRN_DT) AS MaxChurnInvol,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    WHERE (FI_OUTST_AGE >= 90 AND PD_TV_PROD_ID IS NOT NULL) 
   -- OR (FI_OUTST_AGE >= 90 AND (PD_TV_PROD_ID IS NOT NULL OR PD_VO_PROD_ID IS NOT NULL))
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxChurnInvol) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
INVOLUNTARYMAXCHURNERS AS(
 SELECT DISTINCT c.CONTRATOTV, MaxFechaTV as  MaxChurnInvol
 FROM CHURNERSCRMTV c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.CONTRATOTV = i.ACT_ACCT_CD AND i.MaxChurnInvol = c.MaxFechaTV
   WHERE i.ACT_ACCT_CD IS NOT NULL
   GROUP BY C.CONTRATOTV, MaxFechaTV
),
VOLUNTARYMAXCHURNERS AS(
   SELECT DISTINCT c.CONTRATOTV, MaxFechaTV AS MaxChurnVol
   FROM CHURNERSCRMTV c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.CONTRATOTV = i.ACT_ACCT_CD AND i.MaxChurnInvol = c.MaxFechaTV
   WHERE i.ACT_ACCT_CD IS NULL
   GROUP BY C.CONTRATOTV, MaxFechaTV
),
CHURNERSMES AS(
    SELECT EXTRACT (MONTH FROM MaxfechaTV) as MES, Count(DISTINCT CONTRATOTV) AS NumChurners
    FROM CHURNERSCRMTV
    GROUP BY MES
    ORDER BY MES
),
CHURNMESINVOL AS(
    SELECT EXTRACT (MONTH FROM MaxChurnInvol) as MES, Count(DISTINCT CONTRATOTV) AS NumInvol
    FROM INVOLUNTARYMAXCHURNERS 
    GROUP BY MES
    ORDER BY MES
),
CHURNMESVOL AS(
    SELECT EXTRACT (MONTH FROM MaxChurnVol) as MES, Count(DISTINCT CONTRATOTV) AS NumVol
    FROM VOLUNTARYMAXCHURNERS 
    GROUP BY MES
    ORDER BY MES
)
SELECT c.MES , c.NumChurners as ChurnTotal, i.NumInvol as Involuntary , v.NumVol as Voluntary
FROM CHURNERSMES c INNER JOIN CHURNMESINVOL i ON c.MES = i.MES INNER JOIN CHURNMESVOL v ON c.MES = v.MES
GROUP BY MES, ChurnTotal, Involuntary, Voluntary
ORDER BY MES
