WITH CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" AND ESTADO = "FINALIZADA"
  AND FECHA_FINALIZACION IS NOT NULL AND FECHA_APERTURA IS NOT NULL
  AND EXTRACT (MONTH FROM FECHA_FINALIZACION) = 9
 ORDER BY CONTRATOSO),
CHURNERSCRM AS
( SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM,  MAX(CST_CHRN_DT) AS Maxfecha
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
 GROUP BY CONTRATOCRM
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION)) 
    AND EXTRACT (MONTH FROM Maxfecha) = 9 
 )
SELECT CONTRATOSO, CONTRATOCRM
FROM CHURNERSCRM INNER JOIN CHURNERSSO ON CONTRATOSO = CONTRATOCRM
