WITH CONTRATOSACTIVOS AS(
    SELECT DISTINCT ACT_ACCT_CD, FECHA_EXTRACCION
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION
)
SELECT extract (month from FECHA_EXTRACCION) AS MES, COUNT(DISTINCT ACT_ACCT_CD) AS NumActivos
FROM CONTRATOSACTIVOS
--WHERE EXTRACT (MONTH FROM Maxfecha) = 1
GROUP BY MES
ORDER BY MES ASC
