WITH CONTRATOSACTIVOS AS(
    SELECT DISTINCT ACT_ACCT_CD, FECHA_EXTRACCION as Fecha,
    CASE
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "3P"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "2P - BB+TV"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - BB+VO"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - TV+VO"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NULL THEN "1P - BB"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "1P - TV"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "1P - VO"
    END AS PFLAG
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION, PFLAG
),
ACTIVOSMES AS(
    SELECT DISTINCT extract (month from a.Fecha) AS MES, PFLAG, COUNT( DISTINCT ACT_ACCT_CD) AS NUMACTIVOS
FROM CONTRATOSACTIVOS a
GROUP BY MES, PFLAG)
,
CHURNERSPLAN AS(
    SELECT DISTINCT ACT_ACCT_CD
    , MAX(CST_CHRN_DT) AS MaxfechaP,
    CASE
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "3P"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "2P - BB+TV"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - BB+VO"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - TV+VO"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NULL THEN "1P - BB"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "1P - TV"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "1P - VO"
    END AS PFLAG
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, PFLAG
    HAVING EXTRACT (MONTH FROM MaxfechaP) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
CHURNERSPLANMES AS(
    SELECT DISTINCT extract (month from c.MaxfechaP) AS MES, PFLAG, COUNT (DISTINCT ACT_ACCT_CD) AS NUMCHURNERS
FROM CHURNERSPLAN c
GROUP BY MES, PFLAG)
SELECT a.MES, a.PFLAG, a.NUMACTIVOS, c.NUMCHURNERS
FROM ACTIVOSMES a INNER JOIN CHURNERSPLANMES c ON a.MES = c.MES AND a.PFLAG = c.PFLAG
GROUP BY a.MES, PFLAG, a.NUMACTIVOS, c.NUMCHURNERS
ORDER BY a.MES ASC, PFLAG DESC
