WITH CHURNERSVO AS(
     SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOSVO, MAX(CST_CHRN_DT) AS MaxfechaVO
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_VO_PROD_ID IS NOT NULL
   GROUP BY CONTRATOSVO
    HAVING EXTRACT (MONTH FROM MaxfechaVO) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSVO AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('TELEFONIA',  'HOGARES CONECTADOS') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA
),
CRUCECOLLECTIONSVO AS(
    SELECT DISTINCT CONTRATOSVO, CONTRATO, MaxfechaVO
    FROM CHURNERSVO LEFT JOIN MOROSOSVO ON CONTRATOSVO = CONTRATO AND DATE_DIFF (MaxfechaVO, FECHA_FACTURA, DAY) >= 90
    GROUP BY CONTRATOSVO, CONTRATO,MaxfechaVO
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOSVO, MaxfechaVO,
    CASE WHEN CONTRATO IS NULL THEN "Voluntario"
    WHEN CONTRATO IS NOT NULL THEN "Involuntario"
    END AS TipoChurn
    FROM CRUCECOLLECTIONSVO
    GROUP BY CONTRATOSVO, MAXFECHAVO, TipoChurn
)
SELECT EXTRACT (MONTH FROM MAXFECHAVO) AS MES, TIPOCHURN, COUNT(DISTINCT CONTRATOSVO)
FROM CLASIFICACIONCHURN
GROUP BY MES, TIPOCHURN
ORDER BY MES ASC, TIPOCHURN DESC
