WITH CONTRATOSACTIVOS AS(
    SELECT DISTINCT ACT_ACCT_CD, EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, MAX(FECHA_EXTRACCION) AS FECHABASE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION
),
PROVINCIAACTIVOS AS(
    SELECT DISTINCT a.ACT_ACCT_CD, trim(t.ACT_PRVNC_CD) as Provincia, MES, FECHABASE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
    INNER JOIN CONTRATOSACTIVOS a ON t.ACT_ACCT_CD = a.ACT_ACCT_CD AND t.FECHA_EXTRACCION = a.FECHABASE
),
ACTIVOSMESPROVINCIA AS(
    SELECT DISTINCT MES, PROVINCIA, COUNT(DISTINCT ACT_ACCT_CD) AS NumActivos
    FROM PROVINCIAACTIVOS 
    GROUP BY MES, PROVINCIA
),
CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(date(CST_CHRN_DT)) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION)) AND EXTRACT(YEAR FROM Maxfecha) = 2021
),
PROVINCIACHURNERS AS(
    SELECT DISTINCT ACT_ACCT_CD, trim(ACT_PRVNC_CD) as Provincia, date(CST_CHRN_DT) as CST_CHRN_DT
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
),
PROVINCIAREALCHURNERS AS(
    SELECT DISTINCT c.ACT_ACCT_CD, p.Provincia, c.Maxfecha
    FROM CHURNERSCRM c INNER JOIN PROVINCIACHURNERS p ON c.ACT_ACCT_CD = p.ACT_ACCT_CD AND c.Maxfecha = p.CST_CHRN_DT
),
CHURNERSMESPROVINCIA AS(
    SELECT EXTRACT(MONTH FROM MAXFECHA) AS MESCHURN, PROVINCIA, COUNT(DISTINCT ACT_ACCT_CD) AS NumChurners
    FROM PROVINCIAREALCHURNERS
    GROUP BY MESCHURN, PROVINCIA
)
SELECT DISTINCT a.MES, a.PROVINCIA, a.NumActivos, c.NumChurners, ROUND(c.NumChurners/a.NumActivos,3) as churnrate
FROM ACTIVOSMESPROVINCIA a INNER JOIN CHURNERSMESPROVINCIA c ON a.MES = c.MESCHURN AND a.Provincia = c.Provincia
ORDER BY MES, a. Provincia
