WITH 
CHURNERSCRM AS(
     SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS MaxfechaC
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxfechaC) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
PRIMERCHURN AS(
    SELECT DISTINCT ACT_ACCT_CD,MIN(CST_CHRN_DT) MinFecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D` t
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT(YEAR FROM Minfecha) = 2021
),
CRUCEMAXMINCHURN AS(
    SELECT DISTINCT c.ACT_ACCT_CD, p.MinFecha, c.MaxfechaC
    FROM CHURNERSCRM c INNER JOIN PRIMERCHURN p ON c.ACT_ACCT_CD = p.ACT_ACCT_CD AND c.MaxfechaC >= p.MinFecha
),
PLANCHURNERS AS(
      SELECT DISTINCT ACT_ACCT_CD
    , MIN(CST_CHRN_DT) AS MinfechaP,
    CASE
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "3P"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "2P - BB+TV"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - BB+VO"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - TV+VO"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NULL THEN "1P - BB"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "1P - TV"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "1P - VO"
    END AS PFLAG
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, PFLAG
    HAVING extract(YEAR FROM MinfechaP) = 2021
),
CRUCEPLANCHURN AS
(
 SELECT DISTINCT c.ACT_ACCT_CD,c.maxFechaC, p.Pflag, min(date(t.ACT_ACCT_INST_DT)) as MinInst
 FROM CRUCEMAXMINCHURN  c INNER JOIN PLANCHURNERS p on C.ACT_ACCT_CD = p.ACT_ACCT_CD AND c.MinFecha = p.MinFechaP
 INNER JOIN `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D` t
 ON c.ACT_ACCT_CD = t.ACT_ACCT_CD AND c.MaxfechaC = t.CST_CHRN_DT
 GROUP BY c.ACT_ACCT_CD, c.MaxfechaC, p.PFLAG, c.Minfecha
),
TENURECHURN AS(
    SELECT DISTINCT ACT_ACCT_CD, C.MaxfechaC, Pflag,
    CASE WHEN DATE_DIFF( C.MaxfechaC, c.MinInst, DAY)<=180 AND c.MinInst<C.MaxfechaC THEN "<6M"
    WHEN DATE_DIFF(C.MaxfechaC, c.MinInst, DAY)>180 AND DATE_DIFF(C.MaxfechaC, c.MinInst, DAY)<=360 THEN "06-1Y"
    WHEN DATE_DIFF(C.MaxfechaC, c.MinInst, DAY)>360 AND DATE_DIFF(C.MaxfechaC, c.MinInst, DAY)<= 720 THEN "1Y-2Y"
    WHEN DATE_DIFF(C.MaxfechaC, c.MinInst, DAY)>720 THEN ">2Y" END AS TENURE,
    FROM CRUCEPLANCHURN c
    GROUP BY ACT_ACCT_CD, PFLAG, Tenure, c.maxFechaC
)
SELECT DISTINCT EXTRACT (MONTH FROM MaxfechaC) as MES, PFLAG
, TENURE, 
Count(DISTINCT ACT_ACCT_CD) AS NumChurners
FROM TENURECHURN
GROUP BY MES, PFLAG, TENURE
ORDER BY MES, TENURE ASC
