-------------------------------------------- INVOLUNTARY CHURNERS-------------------------------------------------------------------
##USUARIOS QUE ENTRARON EN MORA 
WITH SOFT_DISCONECT AS(
SELECT NOMBRE_CONTRATO, MAX(FECHA_FINALIZACION) AS FECHA_FINALIZACION_SUSPENSION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
WHERE MOTIVO_ORDEN = "SUSPENSION-Orden de servicio" AND ESTADO = "FINALIZADA" 
GROUP BY NOMBRE_CONTRATO
),
## ACTIVADOS
ACTIVADOS AS(
 SELECT NOMBRE_CONTRATO, MAX(FECHA_FINALIZACION) AS FECHA_FINALIZACION_ACTIVACION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
WHERE MOTIVO_ORDEN = "ACTIVACION-Orden de servicio" AND ESTADO = "FINALIZADA"
GROUP BY NOMBRE_CONTRATO
),

##LEFT JOIN 
JOIN_SUSPENDIDOS_ACTIVADOS AS(SELECT a.*,b.FECHA_FINALIZACION_ACTIVACION 
FROM SOFT_DISCONECT a
LEFT JOIN ACTIVADOS b
ON a.NOMBRE_CONTRATO = b.NOMBRE_CONTRATO
),

#SELECT * FROM JOIN_SUSPENDIDOS_ACTIVADOS 

##SUSPENDIDOS SIN REACTIVACION

SUSPENDIDOS_DEF AS (
    SELECT *,CASE WHEN FECHA_FINALIZACION_ACTIVACION > FECHA_FINALIZACION_SUSPENSION THEN 0 ELSE 1 END AS SUSPENDIDOS_SINACTIVACION
    FROM JOIN_SUSPENDIDOS_ACTIVADOS
),
#SELECT * FROM SUSPENDIDOS_DEF

##CHURNES INVOLUNTARIOS
DESINSTALADOS AS(
  SELECT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOD,EXTRACT(month from max(FECHA_APERTURA)) AS MONTH_APERTURA
  FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
  WHERE TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
  AND NOMBRE_CONTRATO IN (SELECT NOMBRE_CONTRATO FROM SUSPENDIDOS_DEF WHERE SUSPENDIDOS_SINACTIVACION =1 AND FECHA_APERTURA > FECHA_FINALIZACION_SUSPENSION)
  GROUP BY NOMBRE_CONTRATO
),
CHURNERSCRUCE AS
(SELECT DISTINCT MESC, FORMATOCONTRATOCRM, MAXFECHA
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-15_ChurnersDefinitivos_D`
GROUP BY MESC, FORMATOCONTRATOCRM, MAXFECHA
),
CHURNERSINVOL AS(
 SELECT DISTINCT MESC, FORMATOCONTRATOCRM, CONTRATOD
 FROM CHURNERSCRUCE c LEFT JOIN DESINSTALADOS d ON c.FORMATOCONTRATOCRM = d.CONTRATOD 
 GROUP BY MESC, FORMATOCONTRATOCRM, CONTRATOD
)
SELECT MESC, COUNT(DISTINCT FORMATOCONTRATOCRM) AS CHURNERS, COUNT (DISTINCT CONTRATOD) AS INVOLUNTARIOS
FROM CHURNERSINVOL
GROUP BY MESC
ORDER BY MESC
