WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha,
    CASE WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=90 AND Max(ACT_ACCT_INST_DT)<MAX(CST_CHRN_DT) THEN "<3M"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=180 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>90 THEN "03-6M"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=270 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>180 THEN "06-9M"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=360 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>270 THEN "09-1A"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=720 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>360 THEN "1-2 A"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=1080 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>720 THEN "2-3 A"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)<=1440 AND DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>1080 THEN "3-4 A"
    WHEN DATE_DIFF(MAX(CST_CHRN_DT), Max(ACT_ACCT_INST_DT), DAY)>1440 THEN "+4A" END AS TENURE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MAX(CST_CHRN_DT)) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
)
SELECT DISTINCT EXTRACT (MONTH FROM Maxfecha) as MES, TENURE,
Count(DISTINCT ACT_ACCT_CD) AS NumChurners
FROM CHURNERSCRM
GROUP BY MES, TENURE
ORDER BY MES, TENURE ASC
