WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha,  Extract(Month from Max(CST_CHRN_DT)) AS MesChurnF
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
FIRSTCHURN AS(
 SELECT DISTINCT ACT_ACCT_CD, Min(CST_CHRN_DT) AS PrimerChurn, Extract(Month from Min(CST_CHRN_DT)) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.ACT_ACCT_CD = f.ACT_ACCT_CD AND f.PrimerChurn <= c.MaxFecha
   GROUP BY ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

INVOLUNTARYCHURNERS AS(
 SELECT DISTINCT ACT_ACCT_CD, Min(CST_CHRN_DT) AS InvolChurnDate,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    WHERE (FI_OUTST_AGE >= 60 AND PD_BB_PROD_ID IS NOT NULL) 
   OR (FI_OUTST_AGE >= 90 AND (PD_TV_PROD_ID IS NOT NULL OR PD_VO_PROD_ID IS NOT NULL))
    GROUP BY ACT_ACCT_CD
),
CHURNTYPEFINALCHURNERS AS(
 SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP,
 CASE WHEN i.ACT_ACCT_CD IS NULL THEN C.ACT_ACCT_CD END AS Voluntario,
 CASE WHEN i.ACT_ACCT_CD IS NOT NULL THEN C.ACT_ACCT_CD END AS Involuntario
 FROM REALCHURNERS c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.ACT_ACCT_CD = i.ACT_ACCT_CD AND i.InvolChurnDate <= MaxFecha
GROUP BY ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP, Voluntario, Involuntario
),
TENURECHURNERS AS(
 SELECT DISTINCT ACT_ACCT_CD, MIN(CST_CHRN_DT) as MinChurnDate,
 CASE   WHEN MAX(C_CUST_AGE) <= 1 THEN "1M"
        WHEN MAX(C_CUST_AGE) > 1 AND MAX(C_CUST_AGE) <= 2 THEN "1M-2M"
        WHEN MAX(C_CUST_AGE) > 2 AND MAX(C_CUST_AGE) <= 3 THEN "2M-3M"
        WHEN MAX(C_CUST_AGE) > 3 AND MAX(C_CUST_AGE) <= 4 THEN "3M-4M"
        WHEN MAX(C_CUST_AGE) > 4 AND MAX(C_CUST_AGE) <= 5 THEN "4M-5M"
        WHEN MAX(C_CUST_AGE) > 5 AND MAX(C_CUST_AGE) <= 6 THEN "5M-6M"
        WHEN MAX(C_CUST_AGE) > 6 AND MAX(C_CUST_AGE) <= 7 THEN "6M-7M"
        WHEN MAX(C_CUST_AGE) > 7 AND MAX(C_CUST_AGE) <= 8 THEN "7M-8M"
        WHEN MAX(C_CUST_AGE) > 8 AND MAX(C_CUST_AGE) <= 9 THEN "8M-9M"
        WHEN MAX(C_CUST_AGE) > 9 AND MAX(C_CUST_AGE) <= 10 THEN "9M-10M"
        WHEN MAX(C_CUST_AGE) > 10 AND MAX(C_CUST_AGE) <= 11 THEN "10M-11M"
        WHEN MAX(C_CUST_AGE) > 11 AND MAX(C_CUST_AGE) <= 12 THEN "11M-1Y"
        WHEN MAX(C_CUST_AGE) > 12 AND MAX(C_CUST_AGE) <= 24 THEN "1Y-2Y"
        WHEN MAX(C_CUST_AGE) > 24 THEN "2Y+"
        END AS TENURE
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` 
 GROUP BY ACT_ACCT_CD
),
CHURNTYPETENURE AS(
    SELECT DISTINCT c.*, t.Tenure
    FROM CHURNTYPEFINALCHURNERS c INNER JOIN TENURECHURNERS t ON c.ACT_ACCT_CD = t.ACT_ACCT_CD AND c.PrimerChurn = t.MinChurnDate
)
SELECT MesChurnF, Tenure, COUNT (DISTINCT ACT_ACCT_CD) AS Churners, COUNT (DISTINCT Voluntario) AS Voluntarios, COUNT (DISTINCT Involuntario) as Involuntarios
FROM CHURNTYPETENURE
GROUP BY MesChurnF, Tenure
ORDER BY MesChurnF, Tenure
