WITH CHURNERSBB AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOSBB, MAX(CST_CHRN_DT) AS MaxfechaBB
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_BB_PROD_ID IS NOT NULL
    GROUP BY CONTRATOSBB
    HAVING EXTRACT (MONTH FROM MaxfechaBB) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSBB AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('INTERNET', 'FTTH (JASEC)', 'HOGARES CONECTADOS') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA
),
CRUCECOLLECTIONSBB AS(
    SELECT DISTINCT CONTRATOSBB, CONTRATO, MaxfechaBB
    FROM CHURNERSBB LEFT JOIN MOROSOSBB ON CONTRATOSBB = CONTRATO AND DATE_DIFF (MaxfechaBB, FECHA_FACTURA, DAY) >= 60
    GROUP BY CONTRATOSBB, CONTRATO,MaxfechaBB
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOSBB, MaxfechaBB,
    CASE WHEN CONTRATO IS NULL THEN "Voluntario"
    WHEN CONTRATO IS NOT NULL THEN "Involuntario"
    END AS TipoChurn
    FROM CRUCECOLLECTIONSBB
    GROUP BY CONTRATOSBB, MAXFECHABB, TipoChurn
)
SELECT EXTRACT (MONTH FROM MAXFECHABB) AS MES, TIPOCHURN, COUNT(DISTINCT CONTRATOSBB)
FROM CLASIFICACIONCHURN
GROUP BY MES, TIPOCHURN
ORDER BY MES ASC, TIPOCHURN DESC
