WITH RGUSACTIVOSBB AS(
    SELECT EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, COUNT(DISTINCT ACT_ACCT_CD) AS ACTIVOSBB
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_BB_PROD_ID IS NOT NULL
    GROUP BY MES
),
RGUSACTIVOSTV AS(
    SELECT EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, COUNT(DISTINCT ACT_ACCT_CD) AS ACTIVOSTV
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_TV_PROD_ID IS NOT NULL
    GROUP BY MES
),
RGUSACTIVOSVO AS(
        SELECT EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, COUNT(DISTINCT ACT_ACCT_CD) AS ACTIVOSVO
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE PD_VO_PROD_ID IS NOT NULL
    GROUP BY MES
)
SELECT b.MES, b.ACTIVOSBB as RGUsBB, t.ACTIVOSTV as RGUsTV, v.ACTIVOSVO as RGUsVO, SUM(b.ACTIVOSBB + t.ACTIVOSTV + v.ACTIVOSVO)
FROM RGUSACTIVOSBB b INNER JOIN RGUSACTIVOSTV t on b.MES = t.MES INNER JOIN RGUSACTIVOSVO v on b.mes = v.mes
GROUP BY MES, RGUsBB, RGUsTV, RGUsVO
ORDER BY MES ASC
