WITH CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS MaxfechaCRM
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxfechaCRM) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA, TIPO_SERVICIO
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('INTERNET', 'FTTH (JASEC)', 'HOGARES CONECTADOS','TELEFONIA','CABLE TICA') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA, TIPO_SERVICIO
),
CRUCECOLLECTIONSCRM AS(
    SELECT DISTINCT CONTRATOCRM, CONTRATO, MaxfechaCRM
    FROM CHURNERSCRM LEFT JOIN MOROSOSCRM ON CONTRATOCRM = CONTRATO  AND ((DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >= 60  AND TIPO_SERVICIO IN('INTERNET', 'FTTH (JASEC)'))
    OR (DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >=90 AND TIPO_SERVICIO IN('HOGARES CONECTADOS','TELEFONIA','CABLE TICA')))
    GROUP BY CONTRATOCRM, CONTRATO,MaxfechaCRM
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOCRM, MaxfechaCRM,
    CASE WHEN CONTRATO IS NULL THEN CONTRATOCRM END AS VOLUNTARIO,
    CASE WHEN CONTRATO IS NOT NULL THEN CONTRATOCRM END AS INVOLUNTARIO
    FROM CRUCECOLLECTIONSCRM
    GROUP BY CONTRATOCRM, MAXFECHACRM, VOLUNTARIO, INVOLUNTARIO
)
SELECT EXTRACT (MONTH FROM MAXFECHACRM) AS MES, COUNT(DISTINCT CONTRATOCRM) AS CHURNERS, COUNT (DISTINCT VOLUNTARIO) AS VOL, COUNT (DISTINCT INVOLUNTARIO) AS INVOL
FROM CLASIFICACIONCHURN
GROUP BY MES
ORDER BY MES ASC
