WITH CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS MaxfechaCRM
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxfechaCRM) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('INTERNET', 'FTTH (JASEC)', 'HOGARES CONECTADOS','TELEFONIA','CABLE TICA') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA
),
CRUCECOLLECTIONSCRM AS(
    SELECT DISTINCT CONTRATOCRM, CONTRATO, MaxfechaCRM
    FROM CHURNERSCRM LEFT JOIN MOROSOSCRM ON CONTRATOCRM = CONTRATO  AND DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >= 60 --OR DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >=90)
    GROUP BY CONTRATOCRM, CONTRATO,MaxfechaCRM
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOCRM, MaxfechaCRM,
    CASE WHEN CONTRATO IS NULL THEN "Voluntario"
    WHEN CONTRATO IS NOT NULL THEN "Involuntario"
    END AS TipoChurn
    FROM CRUCECOLLECTIONSCRM
    GROUP BY CONTRATOCRM, MAXFECHACRM, TipoChurn
),
PRIMERCHURN AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOMIN,MIN(DATE(CST_CHRN_DT)) AS MinFecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT(YEAR FROM Minfecha) = 2021
),
CRUCEMAXMINCHURN AS(
    SELECT DISTINCT c.CONTRATOCRM, p.MinFecha, c.MaxfechaCRM
    FROM CLASIFICACIONCHURN  c INNER JOIN PRIMERCHURN p ON c.CONTRATOCRM = p.CONTRATOMIN AND c.MaxfechaCRM >= p.MinFecha
    --WHERE c.TipoChurn = "Involuntario"
    WHERE c.TipoChurn = "Voluntario"
),
PLANCHURNERS AS(
      SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPLAN
    , MIN(DATE(CST_CHRN_DT)) AS MinfechaP,
    CASE
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "3P"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "2P - BB+TV"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - BB+VO"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - TV+VO"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NULL THEN "1P - BB"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "1P - TV"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "1P - VO"
    END AS PFLAG
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD, PFLAG
    HAVING extract(YEAR FROM MinfechaP) = 2021
),
CRUCEPLANCHURN AS
(
 SELECT DISTINCT c.CONTRATOCRM,c.maxFechaCRM, p.Pflag, min(date(t.ACT_ACCT_INST_DT)) as MinInst
 FROM CRUCEMAXMINCHURN  c INNER JOIN PLANCHURNERS p on C.CONTRATOCRM = p.CONTRATOPLAN AND c.MinFecha = p.MinFechaP
 INNER JOIN `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
 ON c.CONTRATOCRM = RIGHT(CONCAT('0000000000',T.ACT_ACCT_CD) ,10) AND c.MaxfechaCRM = DATE(t.CST_CHRN_DT)
 GROUP BY c.CONTRATOCRM, c.MaxfechaCRM, p.PFLAG, c.Minfecha
),
TENURECHURN AS(
    SELECT DISTINCT C.CONTRATOCRM, C.MaxfechaCRM, Pflag,
    CASE WHEN DATE_DIFF( C.MaxfechaCRM, c.MinInst, DAY)<=180 AND c.MinInst<C.MaxfechaCRM THEN "<6M"
    WHEN DATE_DIFF(C.MaxfechaCRM, c.MinInst, DAY)>180 AND DATE_DIFF(C.MaxfechaCRM, c.MinInst, DAY)<=360 THEN "06-1Y"
    WHEN DATE_DIFF(C.MaxfechaCRM, c.MinInst, DAY)>360 AND DATE_DIFF(C.MaxfechaCRM, c.MinInst, DAY)<= 720 THEN "1Y-2Y"
    WHEN DATE_DIFF(C.MaxfechaCRM, c.MinInst, DAY)>720 THEN "2Y+" END AS TENURE,
    FROM CRUCEPLANCHURN c
    GROUP BY C.CONTRATOCRM, PFLAG, Tenure, c.maxFechaCRM
)
SELECT DISTINCT EXTRACT (MONTH FROM MaxfechaCRM) as MES, PFLAG
, TENURE, 
Count(DISTINCT CONTRATOCRM) AS NumChurners
FROM TENURECHURN
GROUP BY MES, PFLAG, TENURE
ORDER BY MES, TENURE ASC
