--CRUCE CHURNERS TOTALES CRM CON NORETENIDOS
WITH CHURNERSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD),10) AS CONTRATO, MAX(CST_CHRN_DT) AS Maxfecha,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
--    WHERE EXTRACT(YEAR FROM CST_CHRN_DT)=2021
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
    AND EXTRACT (MONTH FROM Maxfecha) < 12
),

NORETENIDOS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',Contrato) ,10) AS Contrato, MAX(FECHA_FINALIZACION) AS FechaTiquete
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL AND SOLUCION_FINAL="NO RETENIDO"
--AND EXTRACT(YEAR FROM FECHA_FINALIZACION)=2021
GROUP BY Contrato
HAVING EXTRACT (MONTH FROM FechaTiquete) < 12
),

CONTRATOSCRM AS(
SELECT DISTINCT EXTRACT(MONTH FROM MaxFecha) as MesCRM, CONTRATO
FROM CHURNERSCRM
--WHERE EXTRACT(YEAR FROM MaxFecha)=2021
),

CONTRATOSNORET AS(
SELECT DISTINCT EXTRACT(MONTH FROM FechaTiquete) as Mesret, CONTRATO
FROM NORETENIDOS
WHERE EXTRACT(YEAR FROM FechaTiquete)=2021
)

SELECT --mesret, 
count( distinct c.contrato) as churnersCRM, count(distinct r.contrato) as Noret
from CONTRATOSCRM c RIGHT JOIN CONTRATOSNORET r ON c.Contrato=r.Contrato
-- AND mesret = mescrm
--AND c.MesCRM=r.MesRet 
--where mesret-mescrm <=2 and mescrm-mesret<=2
--GROUP BY MESRET ORDER BY MESRET
/*select Mesret, count(distinct contrato)
from CONTRATOSNORET 
group by mesret order by mesret*/
