WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha,  Extract(Month from Max(CST_CHRN_DT)) AS MesChurnF
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
FIRSTCHURN AS(
 SELECT DISTINCT ACT_ACCT_CD, Min(CST_CHRN_DT) AS PrimerChurn, Extract(Month from Min(CST_CHRN_DT)) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.ACT_ACCT_CD = f.ACT_ACCT_CD AND f.PrimerChurn <= c.MaxFecha
   GROUP BY ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

INVOLUNTARYCHURNERS AS(
 SELECT DISTINCT ACT_ACCT_CD, Min(CST_CHRN_DT) AS InvolChurnDate,
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    WHERE (FI_OUTST_AGE >= 60 AND PD_BB_PROD_ID IS NOT NULL) 
   OR (FI_OUTST_AGE >= 90 AND (PD_TV_PROD_ID IS NOT NULL OR PD_VO_PROD_ID IS NOT NULL))
    GROUP BY ACT_ACCT_CD
),
CHURNTYPEFINALCHURNERS AS(
 SELECT DISTINCT c.ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP,
 CASE WHEN i.ACT_ACCT_CD IS NULL THEN C.ACT_ACCT_CD END AS Voluntario,
 CASE WHEN i.ACT_ACCT_CD IS NOT NULL THEN C.ACT_ACCT_CD END AS Involuntario
 FROM REALCHURNERS c  LEFT JOIN INVOLUNTARYCHURNERS i ON c.ACT_ACCT_CD = i.ACT_ACCT_CD AND i.InvolChurnDate <= MaxFecha
GROUP BY ACT_ACCT_CD, MaxFecha, PrimerChurn, MesChurnF, MesChurnP, Voluntario, Involuntario
)
SELECT MesChurnF, COUNT (DISTINCT ACT_ACCT_CD) AS Churners, COUNT (DISTINCT Voluntario) AS Voluntarios, COUNT (DISTINCT Involuntario) as Involuntarios
FROM CHURNTYPEFINALCHURNERS
GROUP BY MesChurnF
ORDER BY MesChurnF
