WITH CHURNERSCRUCE AS
(SELECT DISTINCT MESC, FORMATOCONTRATOCRM, MAXFECHA
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-15_ChurnersDefinitivos_D`
GROUP BY MESC, FORMATOCONTRATOCRM, MAXFECHA
),
CLASIFICACIONBAJAS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATOCL, TIPO, MAX(FECHA) AS ULTIMADX
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-01_CR_BAJAS_VOLUNTARIAS_E_INVOLUNTARIAS_2021-01_A_2021-12_T ` 
GROUP BY CONTRATOCL, TIPO
)
SELECT MESC, COUNT(DISTINCT FORMATOCONTRATOCRM) AS CHURNERS, TIPO, COUNT (DISTINCT CONTRATOCL) AS CLASIFICADOS
FROM CHURNERSCRUCE LEFT JOIN CLASIFICACIONBAJAS ON FORMATOCONTRATOCRM = CONTRATOCL  AND MAXFECHA>=ULTIMADX AND DATE_DIFF(MAXFECHA, ULTIMADX, MONTH) <= 3
GROUP BY MESC, TIPO
ORDER BY MESC, TIPO
