WITH CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS MaxfechaCRM
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM MaxfechaCRM) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
MOROSOSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',CONTRATO) ,10) AS CONTRATO, FECHA_FACTURA
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_COLLECTIONS_TOTAL_2021-01_A_2021-11_D`
    WHERE TIPO_SERVICIO IN ('INTERNET', 'FTTH (JASEC)', 'HOGARES CONECTADOS','TELEFONIA','CABLE TICA') AND RANGO_FACTURA <> "1-SIN VENCER"
    GROUP BY CONTRATO, FECHA_FACTURA
),
CRUCECOLLECTIONSCRM AS(
    SELECT DISTINCT CONTRATOCRM, CONTRATO, MaxfechaCRM
    FROM CHURNERSCRM LEFT JOIN MOROSOSCRM ON CONTRATOCRM = CONTRATO  AND DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >= 60 --OR DATE_DIFF (MaxfechaCRM, FECHA_FACTURA, DAY) >=90)
    GROUP BY CONTRATOCRM, CONTRATO,MaxfechaCRM
),
CLASIFICACIONCHURN AS(
    SELECT DISTINCT CONTRATOCRM, MaxfechaCRM,
    CASE WHEN CONTRATO IS NULL THEN "Voluntario"
    WHEN CONTRATO IS NOT NULL THEN "Involuntario"
    END AS TipoChurn
    FROM CRUCECOLLECTIONSCRM
    GROUP BY CONTRATOCRM, MAXFECHACRM, TipoChurn
)
SELECT EXTRACT (MONTH FROM MAXFECHACRM) AS MES, TIPOCHURN, COUNT(DISTINCT CONTRATOCRM)
FROM CLASIFICACIONCHURN
GROUP BY MES, TIPOCHURN
ORDER BY MES ASC, TIPOCHURN DESC
