WITH CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
TENURECHURNERS AS(
    SELECT DISTINCT ACT_ACCT_CD, MAX(CST_CHRN_DT) AS CHURNTENURE,
    CASE 
        WHEN Max(C_CUST_AGE) <= 1 THEN "1M"
        WHEN Max(C_CUST_AGE) > 1 AND Max(C_CUST_AGE) <= 2 THEN "1M-2M"
        WHEN Max(C_CUST_AGE) > 2 AND Max(C_CUST_AGE) <= 3 THEN "2M-3M"
        WHEN Max(C_CUST_AGE) > 3 AND Max(C_CUST_AGE) <= 4 THEN "3M-4M"
        WHEN Max(C_CUST_AGE) > 4 AND Max(C_CUST_AGE) <= 5 THEN "4M-5M"
        WHEN Max(C_CUST_AGE) > 5 AND Max(C_CUST_AGE) <= 6 THEN "5M-6M"
        WHEN Max(C_CUST_AGE) > 6 AND Max(C_CUST_AGE) <= 7 THEN "6M-7M"
        WHEN Max(C_CUST_AGE) > 7 AND Max(C_CUST_AGE) <= 8 THEN "7M-8M"
        WHEN Max(C_CUST_AGE) > 8 AND Max(C_CUST_AGE) <= 9 THEN "8M-9M"
        WHEN Max(C_CUST_AGE) > 9 AND Max(C_CUST_AGE) <= 10 THEN "9M-10M"
        WHEN Max(C_CUST_AGE) > 10 AND Max(C_CUST_AGE) <= 11 THEN "10M-11M"
        WHEN Max(C_CUST_AGE) > 11 AND Max(C_CUST_AGE) <= 12 THEN "11M-1Y"
        WHEN Max(C_CUST_AGE) > 12 AND Max(C_CUST_AGE) <= 24 THEN "1Y-2Y"
        WHEN Max(C_CUST_AGE) > 24 THEN "2Y+"
        END AS TENURE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM CHURNTENURE) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
CRUCETENURE AS (
   SELECT DISTINCT c.ACT_ACCT_CD, c.maxfecha, tenure 
   FROM CHURNERSCRM c LEFT JOIN TENURECHURNERS t ON c.ACT_ACCT_CD = t.ACT_ACCT_CD AND c.Maxfecha = t.CHURNTENURE
    GROUP BY C.ACT_ACCT_CD, C.MAXFECHA, TENURE
)
SELECT EXTRACT (MONTH FROM MAXFECHA) AS MES, TENURE, COUNT(DISTINCT ACT_ACCT_CD) AS CHURNERS
FROM CRUCETENURE
GROUP BY MES, TENURE
ORDER BY MES, TENURE
