WITH CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, Min(FECHA_APERTURA) AS FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 GROUP BY CONTRATOSO
 ),

CHURNERSSOCLASIF AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, Min(t.FECHA_APERTURA) AS FECHA_APERTURA,
CASE WHEN SUBMOTIVO = "MOROSIDAD" THEN RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) END AS INVOLUNTARIO,
CASE WHEN SUBMOTIVO <> "MOROSIDAD" THEN RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) END AS VOLUNTARIO
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` t
 INNER JOIN CHURNERSSO s ON RIGHT(CONCAT('0000000000',t.NOMBRE_CONTRATO) ,10)= s.CONTRATOSO AND t.FECHA_APERTURA = s.FECHA_APERTURA
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND t.FECHA_APERTURA IS NOT NULL
 GROUP BY CONTRATOSO, INVOLUNTARIO, VOLUNTARIO
 ),

CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS Maxfecha,DATE_TRUNC(Max(DATE(CST_CHRN_DT)), MONTH) AS MesChurnF
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
FIRSTCHURN AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPCHURN, Min(DATE(CST_CHRN_DT)) AS PrimerChurn, DATE_TRUNC(Min(DATE(CST_CHRN_DT)), MONTH) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT CONTRATOCRM AS CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.CONTRATOCRM = f.CONTRATOPCHURN AND f.PrimerChurn <= c.MaxFecha
   GROUP BY CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

CRUCECHURNERS AS(
SELECT CONTRATOSO, CHURNER, VOLUNTARIO, INVOLUNTARIO, MaxFecha, PrimerChurn, MesChurnF, MesChurnP,
EXTRACT(MONTH FROM s.FECHA_APERTURA ) AS MesS
FROM REALCHURNERS c LEFT JOIN CHURNERSSOCLASIF s ON CONTRATOSO = CHURNER
AND c.Maxfecha >= s.FECHA_APERTURA AND date_diff(c.Maxfecha, s.FECHA_APERTURA, MONTH) <= 3
GROUP BY contratoso, CHURNER, MesS, VOLUNTARIO, INVOLUNTARIO, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
)

SELECT MesChurnF, count (distinct churner) as CHURNERSCRM, count(distinct CONTRATOSO) AS CHURNERSSO, COUNT (DISTINCT VOLUNTARIO) as voluntarios, COUNT(DISTINCT INVOLUNTARIO) AS Involuntarios
FROM CRUCECHURNERS c
GROUP BY MesChurnF
ORDER BY MesChurnF
