WITH 
CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 )
, PRIMERCHURNSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, Min(FECHA_APERTURA) as PrimerChurnSO,
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 GROUP BY CONTRATOSO
 )
, CHURNERSINVOLUNTARIOS AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
  AND SUBMOTIVO = "MOROSIDAD"
 AND FECHA_APERTURA IS NOT NULL
 )
, CHURNTYPEFLAGSO AS(
    SELECT DISTINCT c. CONTRATOSO, c.PrimerChurnSO,
    CASE WHEN t.CONTRATOSO IS NULL THEN c.contratoso END AS VOLUNTARIO,
    CASE WHEN t.CONTRATOSO IS NOT NULL THEN c.CONTRATOSO END AS INVOLUNTARIO
    FROM PRIMERCHURNSO c LEFT JOIN CHURNERSINVOLUNTARIOS t ON c.CONTRATOSO = t.CONTRATOSO AND t.FECHA_APERTURA = c.PrimerChurnSO
)
, CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CHURNER, MAX(DATE(CST_CHRN_DT)) AS Maxfecha,DATE_TRUNC(Max(DATE(CST_CHRN_DT)), MONTH) AS MesChurnF
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING DATE_TRUNC(Maxfecha, MONTH) = DATE_TRUNC(MAX(FECHA_EXTRACCION), MONTH)
)
, FIRSTCHURN AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPCHURN, Min(DATE(CST_CHRN_DT)) AS PrimerChurn, DATE_TRUNC(Min(CST_CHRN_DT), MONTH) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
)
, REALCHURNERS AS(
 SELECT DISTINCT CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.CHURNER = f.CONTRATOPCHURN AND f.PrimerChurn <= c.MaxFecha
   GROUP BY CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
)
, CRUCECHURNERS AS(
SELECT DISTINCT s.CONTRATOSO, CHURNER, MaxFecha, MesChurnF, Voluntario, Involuntario, Max(FECHA_APERTURA) as Fecha_Apertura, PrimerChurn, MesChurnP
FROM REALCHURNERS c INNER JOIN CHURNERSSO s ON CONTRATOSO = CHURNER
AND c.MaxFecha >= s.FECHA_APERTURA AND date_diff(c.MaxFecha, s.FECHA_APERTURA, MONTH) <= 3
INNER JOIN CHURNTYPEFLAGSO f ON s.CONTRATOSO = f.CONTRATOSO
GROUP BY contratoso, CHURNER, MesChurnF, MaxFecha, Voluntario, Involuntario, PrimerChurn, MesChurnP
)
, CHURNERSDEF AS(
SELECT DISTINCT MesChurnF, MaxFecha as FechaChurn, Fecha_Apertura as FechaMaxSO, PrimerChurn, MesChurnP,
 CHURNER AS CONTRATOCRM, CONTRATOSO AS CONTRATOSERVORDER, 
CASE WHEN VOLUNTARIO IS NOT NULL THEN "Voluntario"
WHEN INVOLUNTARIO IS NOT NULL THEN "Involuntario" END AS CHURNTYPEFLAGSO
FROM CRUCECHURNERS
)
, PLANESACTIVOS AS(
SELECT DISTINCT 
  RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS ACT_ACCT_CD, FECHA_EXTRACCION, DATE_TRUNC(FECHA_EXTRACCION, MONTH) AS Mes
, PD_BB_PROD_NM, PD_BB_PROD_ID, PD_TV_PROD_ID, PD_VO_PROD_ID
, BB_FI_TOT_MRC_AMT - BB_FI_TOT_MRC_AMT_DESC AS MONTO, MIN(DATE(CST_CHRN_DT)) AS MinfechaP,
    CASE
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "3P"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "2P - BB+TV"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - BB+VO"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NOT NULL THEN "2P - TV+VO"
    WHEN  PD_BB_PROD_ID IS NOT NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NULL THEN "1P - BB"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NOT NULL AND PD_VO_PROD_ID IS NULL THEN "1P - TV"
    WHEN  PD_BB_PROD_ID IS NULL AND PD_TV_PROD_ID IS NULL AND PD_VO_PROD_ID IS NOT NULL THEN "1P - VO"
    END AS PFLAG,
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` 
GROUP BY 1,2,3,4,5,6,7,8,10
HAVING EXTRACT(YEAR FROM FECHA_EXTRACCION)=2021
)
, CRUCEPLANMINCHURN AS(
    SELECT DISTINCT c.CONTRATOCRM, DATE_TRUNC(c.FechaChurn,MONTH) as MESC, DATE_TRUNC(c.PrimerChurn, MONTH) AS MESMIN
    , p.Pflag--, c.Voluntario, c.Involuntario
    , p.PD_BB_PROD_NM, P.mes,p.Monto
    FROM CHURNERSDEF c INNER JOIN PLANESACTIVOS p on C.CONTRATOCRM =p.ACT_ACCT_CD AND c.PrimerChurn = p.MinFechaP
)
, CATALOGOINTERNET AS (
SELECT DISTINCT RangoVelocidad, Velocida, ActivoInternet
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_CATALOGUE_TV_INTERNET_2021_T` 
GROUP BY 1,2,3
)
, TABLAPRELIMINAR AS(
SELECT DISTINCT MESC,CONTRATOCRM,PFLAG,RangoVelocidad, Monto/Velocida AS PrecioMbp
FROM CRUCEPLANMINCHURN p INNER JOIN CATALOGOINTERNET c ON p.PD_BB_PROD_NM=c.ActivoInternet
GROUP BY 1,2,3,4,5
)

SELECT MesC,PFLAG, RangoVelocidad, ROUND(AVG(PrecioMbp),2) AS PrecioMbp, COUNT(DISTINCT CONTRATOCRM) AS Reg
FROM TABLAPRELIMINAR
GROUP BY 1,2,3
ORDER BY MesC, PFLAG, RangoVelocidad
