WITH ACTIVOSMES AS(
    SELECT DISTINCT ACT_ACCT_CD, EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, MAX(FECHA_EXTRACCION) AS FECHABASE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, MES),
TENUREACTIVOS AS(
 SELECT DISTINCT EXTRACT(MONTH FROM t.FECHA_EXTRACCION) AS MES, t.ACT_ACCT_CD,
 CASE 
        WHEN Max(C_CUST_AGE) <= 1 THEN "1M"
        WHEN Max(C_CUST_AGE) > 1 AND Max(C_CUST_AGE) <= 2 THEN "1M-2M"
        WHEN Max(C_CUST_AGE) > 2 AND Max(C_CUST_AGE) <= 3 THEN "2M-3M"
        WHEN Max(C_CUST_AGE) > 3 AND Max(C_CUST_AGE) <= 4 THEN "3M-4M"
        WHEN Max(C_CUST_AGE) > 4 AND Max(C_CUST_AGE) <= 5 THEN "4M-5M"
        WHEN Max(C_CUST_AGE) > 5 AND Max(C_CUST_AGE) <= 6 THEN "5M-6M"
        WHEN Max(C_CUST_AGE) > 6 AND Max(C_CUST_AGE) <= 7 THEN "6M-7M"
        WHEN Max(C_CUST_AGE) > 7 AND Max(C_CUST_AGE) <= 8 THEN "7M-8M"
        WHEN Max(C_CUST_AGE) > 8 AND Max(C_CUST_AGE) <= 9 THEN "8M-9M"
        WHEN Max(C_CUST_AGE) > 9 AND Max(C_CUST_AGE) <= 10 THEN "9M-10M"
        WHEN Max(C_CUST_AGE) > 10 AND Max(C_CUST_AGE) <= 11 THEN "10M-11M"
        WHEN Max(C_CUST_AGE) > 11 AND Max(C_CUST_AGE) <= 12 THEN "11M-1Y"
        WHEN Max(C_CUST_AGE) > 12 AND Max(C_CUST_AGE) <= 24 THEN "1Y-2Y"
        WHEN Max(C_CUST_AGE) > 24 THEN "2Y+"
        END AS TENURE
     FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D` t INNER JOIN 
    ACTIVOSMES a ON t.ACT_ACCT_CD = a.ACT_ACCT_CD AND a.MES = extract (month from t.FECHA_EXTRACCION) and a.FECHABASE = t.FECHA_EXTRACCION
GROUP BY t.ACT_ACCT_CD, MES)
SELECT t.MES, t.TENURE, COUNT(DISTINCT t.ACT_ACCT_CD)
FROM TENUREACTIVOS t 
GROUP BY MES, TENURE
ORDER BY MES, TENURE
