WITH CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 ),
PRIMERCHURNSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, Min(FECHA_APERTURA) as PrimerChurnSO,
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 GROUP BY CONTRATOSO
 ),
CHURNERSINVOLUNTARIOS AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
  AND SUBMOTIVO = "MOROSIDAD"
 AND FECHA_APERTURA IS NOT NULL
 ),
CHURNTYPEFLAGSO AS(
    SELECT DISTINCT c. CONTRATOSO, c.PrimerChurnSO,
    CASE WHEN t.CONTRATOSO IS NULL THEN c.contratoso END AS VOLUNTARIO,
    CASE WHEN t.CONTRATOSO IS NOT NULL THEN c.CONTRATOSO END AS INVOLUNTARIO
    FROM PRIMERCHURNSO c LEFT JOIN CHURNERSINVOLUNTARIOS t ON c.CONTRATOSO = t.CONTRATOSO AND t.FECHA_APERTURA = c.PrimerChurnSO
),
CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS Maxfecha,DATE_TRUNC(Max(CST_CHRN_DT), MONTH) AS MesChurnF
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING DATE_TRUNC(Maxfecha, MONTH) = DATE_TRUNC(MAX(FECHA_EXTRACCION), MONTH)
),
FIRSTCHURN AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPCHURN, Min(DATE(CST_CHRN_DT)) AS PrimerChurn, DATE_TRUNC(Min(CST_CHRN_DT), MONTH) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT CONTRATOCRM AS CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.CONTRATOCRM = f.CONTRATOPCHURN AND f.PrimerChurn <= c.MaxFecha
   GROUP BY CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

CRUCECHURNERS AS(
SELECT DISTINCT s.CONTRATOSO, CHURNER, MaxFecha, MesChurnF, Voluntario, Involuntario
FROM REALCHURNERS c LEFT JOIN CHURNERSSO s ON CONTRATOSO = CHURNER
AND c.MaxFecha >= s.FECHA_APERTURA AND date_diff(c.MaxFecha, s.FECHA_APERTURA, MONTH) <= 3
LEFT JOIN CHURNTYPEFLAGSO f ON s.CONTRATOSO = f.CONTRATOSO
GROUP BY contratoso, CHURNER, MesChurnF, MaxFecha, Voluntario, Involuntario
)

SELECT
 c.MesChurnF
 , count(distinct CHURNER) as ChurnersCRM, Count(distinct contratoso) AS ChurnersJoinSO, Count (distinct voluntario) as Voluntarios, count (distinct involuntario) as Involuntarios
FROM CRUCECHURners c
GROUP BY c.MesChurnF
Order by c.MesChurnF
