WITH CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
CASE WHEN SUBMOTIVO = "MOROSIDAD" THEN RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) END AS INVOLUNTARIO,
CASE WHEN SUBMOTIVO <> "MOROSIDAD" THEN RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) END AS VOLUNTARIO
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 ),
CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS Maxfecha,Extract(Month from Max(CST_CHRN_DT)) AS MesChurnF
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
),
FIRSTCHURN AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPCHURN, Min(DATE(CST_CHRN_DT)) AS PrimerChurn, Extract(Month from Min(CST_CHRN_DT)) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT CONTRATOCRM AS CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.CONTRATOCRM = f.CONTRATOPCHURN AND f.PrimerChurn <= c.MaxFecha
   GROUP BY CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

CRUCECHURNERS AS(
SELECT CONTRATOSO, CHURNER, VOLUNTARIO, INVOLUNTARIO, MaxFecha, PrimerChurn, MesChurnF, MesChurnP,
EXTRACT(MONTH FROM s.FECHA_APERTURA ) AS MesS
FROM REALCHURNERS c LEFT JOIN CHURNERSSO s ON CONTRATOSO = CHURNER
AND c.PrimerChurn >= s.FECHA_APERTURA AND date_diff(c.PrimerChurn, s.FECHA_APERTURA, MONTH) <= 3
GROUP BY contratoso, CHURNER, MesChurnF, MaxFecha, PrimerChurn, MesChurnP, MesS, VOLUNTARIO, INVOLUNTARIO
),
TENURECHURNERS AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOTENURE, MIN(DATE(CST_CHRN_DT)) as MinChurnDate,
 CASE   WHEN MAX(C_CUST_AGE) <= 1 THEN "1M"
        WHEN MAX(C_CUST_AGE) > 1 AND MAX(C_CUST_AGE) <= 2 THEN "1M-2M"
        WHEN MAX(C_CUST_AGE) > 2 AND MAX(C_CUST_AGE) <= 3 THEN "2M-3M"
        WHEN MAX(C_CUST_AGE) > 3 AND MAX(C_CUST_AGE) <= 4 THEN "3M-4M"
        WHEN MAX(C_CUST_AGE) > 4 AND MAX(C_CUST_AGE) <= 5 THEN "4M-5M"
        WHEN MAX(C_CUST_AGE) > 5 AND MAX(C_CUST_AGE) <= 6 THEN "5M-6M"
        WHEN MAX(C_CUST_AGE) > 6 AND MAX(C_CUST_AGE) <= 7 THEN "6M-7M"
        WHEN MAX(C_CUST_AGE) > 7 AND MAX(C_CUST_AGE) <= 8 THEN "7M-8M"
        WHEN MAX(C_CUST_AGE) > 8 AND MAX(C_CUST_AGE) <= 9 THEN "8M-9M"
        WHEN MAX(C_CUST_AGE) > 9 AND MAX(C_CUST_AGE) <= 10 THEN "9M-10M"
        WHEN MAX(C_CUST_AGE) > 10 AND MAX(C_CUST_AGE) <= 11 THEN "10M-11M"
        WHEN MAX(C_CUST_AGE) > 11 AND MAX(C_CUST_AGE) <= 12 THEN "11M-1Y"
        WHEN MAX(C_CUST_AGE) > 12 AND MAX(C_CUST_AGE) <= 24 THEN "1Y-2Y"
        WHEN MAX(C_CUST_AGE) > 24 THEN "2Y+"
        END AS TENURE
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` 
 GROUP BY ACT_ACCT_CD
),
CHURNTYPETENURE AS(
    SELECT DISTINCT c.*, t.Tenure
    FROM CRUCECHURNERS  c INNER JOIN TENURECHURNERS t ON c.CHURNER = t.CONTRATOTENURE AND c.PrimerChurn = t.MinChurnDate
)
SELECT
 MesChurnF
 , count(distinct CHURNER) as ChurnersCRM, Tenure, Count(distinct contratoso) AS ChurnersJoinSO, Count (distinct voluntario) as Voluntarios, count (distinct involuntario) as Involuntarios
FROM CHURNTYPETENURE
GROUP BY MesChurnF, Tenure
Order by MesChurnF, Tenure
