SELECT CST_CUST_NAME, CST_CUST_ID, ACT_ACCT_CD,ACT_ACCT_INST_DT, C_CUST_AGE, PD_VO_PROD_NM, PD_VO_PROD_ID, PD_BB_PROD_NM, PD_BB_PROD_ID, PD_TV_PROD_CD, PD_TV_PROD_ID,
ROUND(VO_FI_TOT_MRC_AMT,2) AS VO_MRC, ROUND(VO_FI_TOT_MRC_AMT_DESC,2) AS VO_DESC, ROUND(BB_FI_TOT_MRC_AMT,2) AS BB_MRC, ROUND(BB_FI_TOT_MRC_AMT_DESC,2) AS BB_DESC,
ROUND(TV_FI_TOT_MRC_AMT,2) AS TV_MRC, ROUND(TV_FI_TOT_MRC_AMT_DESC,2) AS TV_DESC, ROUND(COALESCE(SAFE_CAST(VO_FI_BILL_AMT_M0 AS FLOAT64),0),2) AS VO_BILL, ROUND(BB_FI_BILL_AMT_M0,2) AS BB_BILL ,ROUND(TV_FI_BILL_AMT_M0,2) AS TV_BILL, FI_OUTST_AGE, FI_BILL_DT_M0,LST_PYM_DT, OLDEST_UNPAID_BILL_DT, ACT_PRVNC_CD, ACT_CANTON_CD, ACT_RGN_CD, TV_ACT_AREA_CD, CST_CHRN_DT, FECHA_EXTRACCION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
where ACT_ACCT_CD = 825985
order by FECHA_EXTRACCION
