SELECT MAX(FECHA_EXTRACCION) AS ULTIMA_FECHA_MES, ACT_ACCT_CD, EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, CST_CUST_NAME,
ROUND(VO_FI_TOT_MRC_AMT,2) AS VO_MRC, ROUND(VO_FI_TOT_MRC_AMT_DESC,2) AS VO_DESC, ROUND(BB_FI_TOT_MRC_AMT,2) AS BB_MRC, ROUND(BB_FI_TOT_MRC_AMT_DESC,2) AS BB_DESC,
ROUND(TV_FI_TOT_MRC_AMT,2) AS TV_MRC, ROUND(TV_FI_TOT_MRC_AMT_DESC,2) AS TV_DESC, ROUND(COALESCE(SAFE_CAST(VO_FI_BILL_AMT_M0 AS FLOAT64),0),2) AS VO_BILL, ROUND(BB_FI_BILL_AMT_M0,2) AS BB_BILL ,ROUND(TV_FI_BILL_AMT_M0,2) AS TV_BILL
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
where ACT_ACCT_CD = 1205565
AND (EXTRACT (MONTH FROM FECHA_EXTRACCION) = 5  
OR EXTRACT (MONTH FROM FECHA_EXTRACCION) = 6
OR  EXTRACT (MONTH FROM FECHA_EXTRACCION) = 7)
GROUP BY 2,3,4,5,6,7,8,9,10,11,12,13
ORDER BY 2,3
