WITH PRUEBA AS
(SELECT * ,
CASE WHEN (VO_FI_TOT_MRC_AMT - VO_FI_TOT_MRC_AMT_DESC)= MRC_MONTH_3 THEN "OK"
ELSE "ERROR" END AS PRUEBAERROR
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
INNER JOIN `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.pruebaschurnersmrcvo` p ON t.ACT_ACCT_CD = p.CST_CUST_ID
WHERE
( FECHA_EXTRACCION="2021-07-31")
)
SELECT PRUEBAERROR, COUNT(*)
FROM PRUEBA
GROUP BY PRUEBAERROR
