CREATE OR REPLACE TABLE `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.--2022-08-25_CR_FinalCRM_202201_202207` AS

SELECT * FROM(
SELECT *
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-08-24_CR_CRM_20210101_20220604` 
WHERE date_trunc(fecha_extraccion, year) = '2022-01-01'
UNION ALL

SELECT ORG_CNTRY,CST_CUST_NAME, CST_CUST_ID,ACT_ACCT_CD, ACT_CONTACT_MAIL_1, ACT_ACCT_INST_DT, ACT_ACCT_SIGN_DT,C_CUST_AGE, PD_VO_PROD_NM, PD_VO_PROD_ID, PD_BB_PROD_NM, PD_BB_PROD_ID, PD_TV_PROD_CD,
PD_TV_PROD_ID, PD_MIX_CD, PD_MIX_NM, VO_FI_TOT_MRC_AMT, VO_FI_TOT_MRC_AMT_DESC, BB_FI_TOT_MRC_AMT, BB_FI_TOT_MRC_AMT_DESC, TV_FI_TOT_MRC_AMT, TV_FI_TOT_MRC_AMT_DESC, CAST(TOT_BILL_AMT AS FLOAT64) AS TOT_BILL_AMT, CAST(TOT_DESC_AMT AS FLOAT64) AS TOT_DESC_AMT, FI_OUTST_AGE,
LOAD_DT, FI_BILL_DT_M0,LST_PYM_DT, OLDEST_UNPAID_BILL_DT, ACT_PRVNC_CD, ACT_CANTON_CD, ACT_RGN_CD, TV_ACT_AREA_CD, ACT_CUST_TYP, ACT_CUST_TYP_NM, CST_CHRN_DT, FECHA_EXTRACCION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-07-27_CRM_Jun5_Jul5`

UNION ALL

SELECT ORG_CNTRY,CST_CUST_NAME, CST_CUST_ID,ACT_ACCT_CD, ACT_CONTACT_MAIL_1, ACT_ACCT_INST_DT, ACT_ACCT_SIGN_DT,C_CUST_AGE, PD_VO_PROD_NM, PD_VO_PROD_ID, PD_BB_PROD_NM, PD_BB_PROD_ID, PD_TV_PROD_CD,
PD_TV_PROD_ID, PD_MIX_CD, PD_MIX_NM, VO_FI_TOT_MRC_AMT, VO_FI_TOT_MRC_AMT_DESC, BB_FI_TOT_MRC_AMT, BB_FI_TOT_MRC_AMT_DESC, TV_FI_TOT_MRC_AMT, TV_FI_TOT_MRC_AMT_DESC, CAST(TOT_BILL_AMT AS FLOAT64) AS TOT_BILL_AMT, CAST(TOT_DESC_AMT AS FLOAT64) AS TOT_DESC_AMT, FI_OUTST_AGE,
LOAD_DT, FI_BILL_DT_M0,LST_PYM_DT, OLDEST_UNPAID_BILL_DT, ACT_PRVNC_CD, ACT_CANTON_CD, ACT_RGN_CD, TV_ACT_AREA_CD, ACT_CUST_TYP, ACT_CUST_TYP_NM, CST_CHRN_DT, FECHA_EXTRACCION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220825_Historical_CRM_Jul_6_30_2022`

UNION ALL
SELECT ORG_CNTRY,CST_CUST_NAME, CST_CUST_ID,ACT_ACCT_CD, ACT_CONTACT_MAIL_1, ACT_ACCT_INST_DT, ACT_ACCT_SIGN_DT,C_CUST_AGE, PD_VO_PROD_NM, PD_VO_PROD_ID, PD_BB_PROD_NM, PD_BB_PROD_ID, PD_TV_PROD_CD,
PD_TV_PROD_ID, PD_MIX_CD, PD_MIX_NM, VO_FI_TOT_MRC_AMT, VO_FI_TOT_MRC_AMT_DESC, BB_FI_TOT_MRC_AMT, BB_FI_TOT_MRC_AMT_DESC, TV_FI_TOT_MRC_AMT, TV_FI_TOT_MRC_AMT_DESC, CAST(TOT_BILL_AMT AS FLOAT64) AS TOT_BILL_AMT, CAST(TOT_DESC_AMT AS FLOAT64) AS TOT_DESC_AMT, FI_OUTST_AGE,
LOAD_DT, FI_BILL_DT_M0,LST_PYM_DT, OLDEST_UNPAID_BILL_DT, ACT_PRVNC_CD, ACT_CANTON_CD, ACT_RGN_CD, TV_ACT_AREA_CD, ACT_CUST_TYP, ACT_CUST_TYP_NM, CST_CHRN_DT, FECHA_EXTRACCION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220825_CRM_Jul31_Ago1` 
)
