CREATE OR REPLACE TABLE `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.CR_ORDENES_SERVICIO_Ene_202_Jul_2022` AS
WITH SERVICEORDERS_Jul AS(
SELECT SITE
    , CLASE
    , MOTIVO
    , CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION
    , TIPO_DE_GESTION
    , TIPO_DE_ORDEN AS TIPO_ORDEN
    , N___DE_ORDEN AS NO_ORDEN
    , DATE(CREADO) AS FECHA_APERTURA
    , SUBMOTIVO
    , ESTADO
    , Nombre_del_contrato AS NOMBRE_CONTRATO
    , PROVINCIA
    , CANT__N as CANTON
    , DISTRITO
    , BARRIO
    , DATE(FECHA_DEL_PEDIDO) AS FECHA_PEDIDO
    , DATE(Fecha_de_finalizaci__n) AS FECHA_FINALIZACION
    , CANAL
    , TIPO_CLIENTE
FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220825_Ordenes_Servicio_Jul_2022`
)

, SERVICEORDERS_Jun2022 AS(

    SELECT * 
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220713_CR_ORDENES_SERVICIO_2021-01_A_2022-06_D`
)

SELECT *
FROM
(SELECT * FROM SERVICEORDERS_Jun2022
UNION ALL
SELECT * FROM SERVICEORDERS_Jul)
ORDER BY 1
