WITH SOFT_DISCONECT AS(
SELECT NOMBRE_CONTRATO, FECHA_APERTURA AS FECHA_FINALIZACION_SUSPENSION
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
WHERE MOTIVO_ORDEN = "SUSPENSION-Orden de servicio"
AND ESTADO = "FINALIZADA" 
GROUP BY NOMBRE_CONTRATO
)
SELECT EXTRACT (MONTH) FROM FECHA_FINALIZACION_SUSPENSION AS MES, COUNT (DISTINCT NOMBRE_CONTRATO)
FROM SOFT_DISCONECT 
