CREATE TEMP FUNCTION RemoveAccentMarks (word STRING)
    RETURNS STRING
AS (
 REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(word, 'á', 'a'), 'é','e'), 'í', 'i'), 'ó', 'o'), 'ú','u') 
)
;
WITH
DISTRITOSIDS AS(
SELECT RemoveAccentMarks(Distrito) AS DistritoSinTildes
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_IDS_DISTRITAL_2021_T` 
),
CONTRATOSACTIVOS AS(
    SELECT DISTINCT ACT_ACCT_CD, EXTRACT(MONTH FROM FECHA_EXTRACCION) AS MES, MAX(FECHA_EXTRACCION) AS FECHA_REPORTE
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION
),

DISTRITOSCRM AS(
SELECT DISTINCT a.ACT_ACCT_CD, TRIM(t.ACT_RGN_CD) AS ACT_RGN_CD, a.Mes
FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D` t
INNER JOIN CONTRATOSACTIVOS a on a.ACT_ACCT_CD = t.ACT_ACCT_CD AND EXTRACT(MONTH FROM t.FECHA_EXTRACCION) = a.MES AND t.FECHA_EXTRACCION = a.FECHA_REPORTE
GROUP BY ACT_ACCT_CD, ACT_RGN_CD, a.Mes
),
DISTRITOSTOTALES AS (
SELECT DISTINCT c.MES, i.DistritoSinTildes, c.ACT_RGN_CD, c.ACT_ACCT_CD
FROM DISTRITOSIDS i RIGHT JOIN DISTRITOSCRM c ON UPPER(i.DistritoSinTildes)=c.ACT_RGN_CD
GROUP BY c.Mes, i.DistritoSinTildes, c.ACT_RGN_CD, c.ACT_ACCT_CD)

SELECT DISTINCT d.MES, d.ACT_RGN_CD , d.distritosintildes, COUNT(DISTINCT d.ACT_ACCT_CD) 
FROM DISTRITOSTOTALES d
GROUP BY d.Mes, d.DistritoSinTildes, d.ACT_RGN_CD
ORDER BY MES, D.ACT_RGN_CD
